apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: guestbook
  version: 0.0.1
  repo: https://achieris.github.io/product-demo-gitops/chart
  valuesFile: values-dev.yaml
