replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/openshift/httpd
  tag: "latest"

service:
  name: nginx-service
  type: ClusterIP
  port: 8080
  targetPort: 8080

